<?php
    $title = "Restaurante Dona Rita";
    $desenvolvedor = "Rafael Alves Florindo / Waldemar Augusto da Silva Filho";

    $pratos = array(
        0 => array('id'=>'1', 
            'titulo'=>'Alcatra', 
            'descricao'=>'Arroz com feijão, alcatra, batata frita, tomate e salada de alface.',
            'preco'=>'R$22,50',
            'imagem'=>'img/arrozcomfeijao.jpg', 
            'title_img'=>'Alcatra'),
        1 => array('id'=>'2', 
            'titulo'=>'Espaguete', 
            'descricao'=>'Espaguete com molho de tomate, carne moida e queijo ralado.',
            'preco'=>'R$19,50',
            'imagem'=>'img/macarraocommolho.jpg', 
            'title_img'=>'Espaguete'),
        2 => array('id'=>'3', 
            'titulo'=>'Feijoada', 
            'descricao'=>'Feijão preto com carne de porco defumada e calabresa.',
            'preco'=>'R$25,00',
            'imagem'=>'img/feijoada.jpg', 
            'title_img'=>'Feijoada'),
        3 => array('id'=>'4', 
            'titulo'=>'Arroz com ovo e Carne', 
            'descricao'=>'Arroz com ovo, patinho, batata frita e Alface.',
            'preco'=>'R$19,50',
            'imagem'=>'img/arrozcomovo.jpg', 
            'title_img'=>'Arroz com ovo'),
        4 => array('id'=>'5', 
            'titulo'=>'Yakisoba', 
            'descricao'=>'Macarrão oriental, filé picadinho, legumes aldentes e molho.',
            'preco'=>'R$20,00',
            'imagem'=>'img/yakisoba.jpg', 
            'title_img'=>'Yakisoba'),
        5 => array('id'=>'6', 
            'titulo'=>'Churrasquinho', 
            'descricao'=>'Carne assada, arroz, batata frita e pimentão',
            'preco'=>'R$20,00',
            'imagem'=>'img/churrasquinho.jpg', 
            'title_img'=>'Churrasquinho'),
        6 => array('id'=>'7', 
            'titulo'=>'Bife de Frango', 
            'descricao'=>'Bife de frango com limão, tomate, pimentão e cenoura na chapa branca.',
            'preco'=>'R$20,00',
            'imagem'=>'img/bifedefrango.jpg', 
            'title_img'=>'Bife de Frango'),
        7 => array('id'=>'8', 
            'titulo'=>'Peixe Frito', 
            'descricao'=>'Postas de Tilápia Frita, alface e tomate cereja',
            'preco'=>'R$28,00',
            'imagem'=>'img/peixe.jpg', 
            'title_img'=>'Peixe Frito'),

    );
